Terraform version is now customizable in downstream jobs
observeinc/.github pull request #53
Opened 2023-02-14 19:30 UTC by obs-gh-kriswagner

2023-02-14 21:50 UTC, bendrucker requested changes

2023-02-14 21:50 UTC, bendrucker commented on .github/workflows/tf-account.yaml
> +env:
Remove this indirection, set a `default` for the input

https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_callinputs

2023-02-14 21:50 UTC, bendrucker commented on .github/workflows/tf-account.yaml
> +    name: 'Run terraform'
Nit, introduced trailing spaces

2023-02-14 21:50 UTC, bendrucker commented on .github/workflows/tf-account.yaml
> +      TERRAFORM_VERSION:
Workflow inputs are very similar to Actions inputs and should use the same conventions:

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs

Meaning this is either `terraform-version` or `terraform_version`. Both are valid, but dash case is canonical.

In an action, inputs are passed through via upper-cased environment variables and are thus case insensitive. In workflow calls, they probably are case sensitive.

Secrets are uppercased, following environment variable conventions.

2023-02-14 21:50 UTC, bendrucker commented on .github/workflows/tf-account.yaml
> +        type: string
Include a description for each input

2023-02-14 21:53 UTC, bendrucker commented
> Jobs can customize the terraform version through the var context

This is not correct

2023-02-14 22:12 UTC, bendrucker commented
Also, I've edited the PR title here for you. The one universal rule to apply is "present tense, imperative mood," which is a widely accepted convention:

https://initialcommit.com/blog/Git-Commit-Message-Imperative-Mood

This is generally the most concise, readable way to express the information. Every change was written in the past and applies in the future so words or suffixes to this effect are extraneous.

I tend to let past tense slide but switching to passive voice I'll usually call out. Commit tense is a programmer debate but active voice is broadly recommended by style guides for non-scientific writing.

Especially now that GitHub renders them in the UI, I like using backticks to wrap identifier names. This turns the title/commit message into ultra-light bit of API documentation while still being roughly as readable as `Accept Terraform version as...`.

2023-02-14 23:46 UTC, obs-gh-kriswagner commented
> > Jobs can customize the terraform version through the var context
> 
> This is not correct. An example of how you expect this to be called would be helpful, including a link to a draft PR where this was tested. Surely that doesn't use `vars`.

I was mostly testing to see how `vars` works. When I was [reading the docs](https://docs.github.com/en/actions/learn-github-actions/contexts#vars-context) on the different contexts I came across `vars` (which is still in beta) and wanted to see if this is something we would want to support as an input option. And it is not

2023-02-15 00:30 UTC, bendrucker approved these changes
Great!

2023-02-15 01:08 UTC, obs-gh-kriswagner commented
Verified this works in the downstream jobs by submitting a draft PR to [terraform-observe-example](https://github.com/observeinc/terraform-observe-example) and you can see the right terraform version being installed in this job https://github.com/observeinc/terraform-observe-example/actions/runs/4179539302/jobs/7239602200

2023-02-15 02:58 UTC, bendrucker approved these changes
Great! A good trick to keep in your pocket for triggering CI workflows:

```sh
git commit --allow-empty --message 'trigger run'
```

2023-02-15 18:48 UTC, merged